### ISSUE TITLE
Dell Latitude 7490

### ISSUE THREAD

**Issue by franklin-gedler** [blankmac/AlpsHID#7]
Hi @juico I have another Dell Latitude 7490 laptop with trackpad issues:

Model: DELL081C

would you have any way to make it work?

**Comment by juico** [comment]
Hey, not sure why it doesn't work. As far as i know someone with the 7490 already has it working, https://osxlatitude.com/forums/topic/16822-latitude-7490-touchpad-close-to-fully-working-with-new-i2c-alps-kext/ . Do you have the I2C itself working? Maybe you can post a IOReg report, that would give a bit more insight.

**Comment by franklin-gedler** [comment]
[Dell_Latitude_7490_IOReg.zip](https://github.com/blankmac/AlpsHID/files/7469411/Dell_Latitude_7490_IOReg.zip)

@juico  Thanks for the prompt response, I tried the kext of the link and I had no luck. I attach the report

**Comment by franklin-gedler** [comment]
attached EFI
[https://drive.google.com/file/d/1_AJqhFDPWo2R678lkDdUarDjHTmFB68L/view?usp=sharing](url)

thanks

**Comment by franklin-gedler** [comment]
Thanks, @juico @Lorys89 I was able to solve it, I had to compile SSDT-GPI0 and SSDT-XOSI, both I added them to the ACPI folder, since I am working thanks
